errors.title=ERROR!!
errors.generic = Polonium crashed with an exception!
error.numberParse = Invalid number: %s
error.cantSave = You cannot leave. Error = %s
error.emptyMole = The file tracker for this mole is empty.
error.taskFailed = Task failed to execute!
error.invalidDays = Days to warn cannot be more than or equal to the days to delete!

mole.title = Polonium Config Editor
mole.header = "Moles" are directories Polonium will decay for deletion.

mole.dialog.add = Select a path to add...
mole.dialog.add.databaseExists = A file database exists for %s. Keep the database or start fresh?
mole.dialog.remove = Are you sure you want to remove %s?
mole.dialog.remove.database = Remove file database for %s? \
  If you decide to keep it, the file tracker will be preserved the next time you add this directory.
mole.dialog.trash.replace = Are you sure you want to overwrite %s for %s?
mole.dialog.trash.success = Restore operation was successful! Saved to %s

mole.tab.paths = Paths
mole.tab.behavior = Behavior
mole.tab.trash = Trash

mole.fields.warn = Days of warning before deletion: 
mole.fields.delete = Days of file deletion: 

file.title = Polonium File Viewer
file.header = These are files that are subject to deletion. The decay of a file is how many days the file is unchanged.

button.add=Add
button.remove=Remove
button.edit=Edit
button.close=Close
button.save=Save
button.saveAndClose = Save and Close
button.view=View
button.save.confirm=Do you want to save the changes?
button.cancel=Cancel
button.more=More
button.open=Open
button.browse=Browse
button.up=^
button.down=v
button.install=Install
button.keep = Keep
button.forget = Forget

about.header = About

ui.task.indeterminate = Working...
ui.task.determinate = %.1f%%
ui.task.complete = Complete!

task.mole.load = Loading mole...
task.mole.save = Saving mole...
task.mole.read = Reading mole...
task.mole.write = Writing mole...

table.unknown = Unknown
table.column.filePath = File Path
table.column.fileDecay = Decay (Days)
table.column.lastModified = Last Modified
table.column.excluded = Excluded?
table.column.fileName = File Name
table.column.fileSize = File Size

popup.file.preempt = Preempt Decay
popup.trash.restore = Restore Item

notifier.title = Polonium
notifier.filesDeleted = Files have been deleted from this system due to decay.\n\
  Here are the files deleted: \n\
  %s
notifier.filesDeletedForever = Files have been fully deleted due to decay and they are never to be seen in broad daylight again.\n\
  Here are the files PERMANENTLY deleted: \n\
  %s
notifier.filesWarn = These are files that are about to get deleted due to decay:\n\
  %s
notifier.options.open = Open Polonium
notifier.options.close = Close
notifier.more = +%d more

trash.entry = %s; trashed %d days ago.