writer1        = console
writer1.format = {date: HH:mm:ss.SSS} {level}: {message}
writer1.level  = trace

writer2          = rolling file
writer2.file     = #{polonium.root_directory}/logs/log-{date}-{pid}-{count}.log
writer2.latest   = #{polonium.root_directory}/logs/latest.log
writer2.convert  = gzip
writer2.format   = {date: HH:mm:ss.SSS} {level}: {message}
writer2.level    = trace

autoshutdown = false